package by.aurorasoft.fuelsearcher.it.argumentsprovider;

import by.aurorasoft.fuelsearcher.it.argumentsprovider.model.FuelSearchingArguments;
import by.aurorasoft.fuelsearcher.model.Fuel;
import by.aurorasoft.fuelsearcher.model.specification.FuelSpecification;

import java.util.stream.Stream;

public final class TwentyFourthTableFuelSearchingArgumentsProvider extends TableFuelSearchingArgumentsProvider {

    @Override
    protected Stream<FuelSearchingArguments> createFuelSearchingArguments() {
        return Stream.of(
                FuelSearchingArguments.builder()
                        .specification(FuelSpecification.builder()
                                .tableName("ПРЯМОЕ КОМБАЙНИРОВАНИЕ ЗЕРНОВЫХ С ИЗМЕЛЬЧЕНИЕМ СОЛОМЫ")
                                .combine("CLAAS LEXION-770 - 524 л.с.")
                                .weightRatioGrainToStraw("1:1")
                                .yield("До 1.4")
                                .workingWidth("10.5")
                                .routingLength("Менее 150")
                                .build())
                        .expected(new Fuel(24.1, 9.5))
                        .build(),
                FuelSearchingArguments.builder()
                        .specification(FuelSpecification.builder()
                                .tableName("ПРЯМОЕ КОМБАЙНИРОВАНИЕ ЗЕРНОВЫХ С ИЗМЕЛЬЧЕНИЕМ СОЛОМЫ")
                                .combine("CLAAS LEXION-770 - 524 л.с.")
                                .weightRatioGrainToStraw("1:1")
                                .yield("4.9...5.3")
                                .workingWidth("12")
                                .routingLength("401-600")
                                .build())
                        .expected(new Fuel(94.7, 3.3))
                        .build(),
                FuelSearchingArguments.builder()
                        .specification(FuelSpecification.builder()
                                .tableName("ПРЯМОЕ КОМБАЙНИРОВАНИЕ ЗЕРНОВЫХ С ИЗМЕЛЬЧЕНИЕМ СОЛОМЫ")
                                .combine("CLAAS LEXION-770 - 524 л.с.")
                                .weightRatioGrainToStraw("1:1.5")
                                .yield("Св. 6")
                                .workingWidth("10.5")
                                .routingLength("201-300")
                                .build())
                        .expected(new Fuel(87.8, 3))
                        .build(),
                FuelSearchingArguments.builder()
                        .specification(FuelSpecification.builder()
                                .tableName("ПРЯМОЕ КОМБАЙНИРОВАНИЕ ЗЕРНОВЫХ С ИЗМЕЛЬЧЕНИЕМ СОЛОМЫ")
                                .combine("CLAAS LEXION-770 - 524 л.с.")
                                .weightRatioGrainToStraw("1:1.5")
                                .yield("5.4...5.7")
                                .workingWidth("12")
                                .routingLength("150-200")
                                .build())
                        .expected(new Fuel(74.1, 3.2))
                        .build(),
                FuelSearchingArguments.builder()
                        .specification(FuelSpecification.builder()
                                .tableName("ПРЯМОЕ КОМБАЙНИРОВАНИЕ ЗЕРНОВЫХ С ИЗМЕЛЬЧЕНИЕМ СОЛОМЫ")
                                .combine("CLAAS LEXION-770 - 524 л.с.")
                                .weightRatioGrainToStraw("1:2")
                                .yield("3...3.3")
                                .workingWidth("10.5")
                                .routingLength("Более 1000")
                                .build())
                        .expected(new Fuel(99.6, 3.4))
                        .build(),
                FuelSearchingArguments.builder()
                        .specification(FuelSpecification.builder()
                                .tableName("ПРЯМОЕ КОМБАЙНИРОВАНИЕ ЗЕРНОВЫХ С ИЗМЕЛЬЧЕНИЕМ СОЛОМЫ")
                                .combine("CLAAS LEXION-770 - 524 л.с.")
                                .weightRatioGrainToStraw("1:2")
                                .yield("4...4.2")
                                .workingWidth("12")
                                .routingLength("201-300")
                                .build())
                        .expected(new Fuel(84.4, 3.2))
                        .build(),
                FuelSearchingArguments.builder()
                        .specification(FuelSpecification.builder()
                                .tableName("ПРЯМОЕ КОМБАЙНИРОВАНИЕ ЗЕРНОВЫХ С ИЗМЕЛЬЧЕНИЕМ СОЛОМЫ")
                                .combine("КЗС-1624-1 \"ПАЛЕССЕ GS-1624-1\" - 490 л.с.")
                                .weightRatioGrainToStraw("1:1")
                                .yield("До 1.4")
                                .workingWidth("9.2")
                                .routingLength("Менее 150")
                                .build())
                        .expected(new Fuel(21.7, 16))
                        .build(),
                FuelSearchingArguments.builder()
                        .specification(FuelSpecification.builder()
                                .tableName("ПРЯМОЕ КОМБАЙНИРОВАНИЕ ЗЕРНОВЫХ С ИЗМЕЛЬЧЕНИЕМ СОЛОМЫ")
                                .combine("КЗС-1624-1 \"ПАЛЕССЕ GS-1624-1\" - 490 л.с.")
                                .weightRatioGrainToStraw("1:1")
                                .yield("7.1...7.5")
                                .workingWidth("9.2")
                                .routingLength("601-1000")
                                .build())
                        .expected(new Fuel(96.9, 4.8))
                        .build(),
                FuelSearchingArguments.builder()
                        .specification(FuelSpecification.builder()
                                .tableName("ПРЯМОЕ КОМБАЙНИРОВАНИЕ ЗЕРНОВЫХ С ИЗМЕЛЬЧЕНИЕМ СОЛОМЫ")
                                .combine("КЗС-1624-1 \"ПАЛЕССЕ GS-1624-1\" - 490 л.с.")
                                .weightRatioGrainToStraw("1:1.5")
                                .yield("3.3...3.6")
                                .workingWidth("9.2")
                                .routingLength("301-400")
                                .build())
                        .expected(new Fuel(73.4, 6.3))
                        .build(),
                FuelSearchingArguments.builder()
                        .specification(FuelSpecification.builder()
                                .tableName("ПРЯМОЕ КОМБАЙНИРОВАНИЕ ЗЕРНОВЫХ С ИЗМЕЛЬЧЕНИЕМ СОЛОМЫ")
                                .combine("КЗС-1624-1 \"ПАЛЕССЕ GS-1624-1\" - 490 л.с.")
                                .weightRatioGrainToStraw("1:1.5")
                                .yield("5.7...6")
                                .workingWidth("9.2")
                                .routingLength("150-200")
                                .build())
                        .expected(new Fuel(61.8, 5.7))
                        .build(),
                FuelSearchingArguments.builder()
                        .specification(FuelSpecification.builder()
                                .tableName("ПРЯМОЕ КОМБАЙНИРОВАНИЕ ЗЕРНОВЫХ С ИЗМЕЛЬЧЕНИЕМ СОЛОМЫ")
                                .combine("КЗС-1624-1 \"ПАЛЕССЕ GS-1624-1\" - 490 л.с.")
                                .weightRatioGrainToStraw("1:2")
                                .yield("2.5...2.7")
                                .workingWidth("9.2")
                                .routingLength("301-400")
                                .build())
                        .expected(new Fuel(70.5, 6.5))
                        .build(),
                FuelSearchingArguments.builder()
                        .specification(FuelSpecification.builder()
                                .tableName("ПРЯМОЕ КОМБАЙНИРОВАНИЕ ЗЕРНОВЫХ С ИЗМЕЛЬЧЕНИЕМ СОЛОМЫ")
                                .combine("КЗС-1624-1 \"ПАЛЕССЕ GS-1624-1\" - 490 л.с.")
                                .weightRatioGrainToStraw("1:2")
                                .yield("4.7...5")
                                .workingWidth("9.2")
                                .routingLength("201-300")
                                .build())
                        .expected(new Fuel(73.4, 5.3))
                        .build(),
                FuelSearchingArguments.builder()
                        .specification(FuelSpecification.builder()
                                .tableName("ПРЯМОЕ КОМБАЙНИРОВАНИЕ ЗЕРНОВЫХ С ИЗМЕЛЬЧЕНИЕМ СОЛОМЫ")
                                .combine("CLAAS LEXION-760 - 461 л.с.")
                                .weightRatioGrainToStraw("1:1")
                                .yield("До 1.4")
                                .workingWidth("9")
                                .routingLength("Менее 150")
                                .build())
                        .expected(new Fuel(21.5, 9.4))
                        .build(),
                FuelSearchingArguments.builder()
                        .specification(FuelSpecification.builder()
                                .tableName("ПРЯМОЕ КОМБАЙНИРОВАНИЕ ЗЕРНОВЫХ С ИЗМЕЛЬЧЕНИЕМ СОЛОМЫ")
                                .combine("CLAAS LEXION-760 - 461 л.с.")
                                .weightRatioGrainToStraw("1:1")
                                .yield("Св. 7.5")
                                .workingWidth("9")
                                .routingLength("Более 1000")
                                .build())
                        .expected(new Fuel(119.2, 2.4))
                        .build(),
                FuelSearchingArguments.builder()
                        .specification(FuelSpecification.builder()
                                .tableName("ПРЯМОЕ КОМБАЙНИРОВАНИЕ ЗЕРНОВЫХ С ИЗМЕЛЬЧЕНИЕМ СОЛОМЫ")
                                .combine("CLAAS LEXION-760 - 461 л.с.")
                                .weightRatioGrainToStraw("1:1.5")
                                .yield("2.7...3")
                                .workingWidth("9")
                                .routingLength("201-300")
                                .build())
                        .expected(new Fuel(53.6, 4.6))
                        .build(),
                FuelSearchingArguments.builder()
                        .specification(FuelSpecification.builder()
                                .tableName("ПРЯМОЕ КОМБАЙНИРОВАНИЕ ЗЕРНОВЫХ С ИЗМЕЛЬЧЕНИЕМ СОЛОМЫ")
                                .combine("CLAAS LEXION-760 - 461 л.с.")
                                .weightRatioGrainToStraw("1:1.5")
                                .yield("5.4...5.7")
                                .workingWidth("9")
                                .routingLength("150-200")
                                .build())
                        .expected(new Fuel(65.7, 3.2))
                        .build(),
                FuelSearchingArguments.builder()
                        .specification(FuelSpecification.builder()
                                .tableName("ПРЯМОЕ КОМБАЙНИРОВАНИЕ ЗЕРНОВЫХ С ИЗМЕЛЬЧЕНИЕМ СОЛОМЫ")
                                .combine("CLAAS LEXION-760 - 461 л.с.")
                                .weightRatioGrainToStraw("1:2")
                                .yield("4.2...4.5")
                                .workingWidth("9")
                                .routingLength("601-1000")
                                .build())
                        .expected(new Fuel(105.5, 2.7))
                        .build(),
                FuelSearchingArguments.builder()
                        .specification(FuelSpecification.builder()
                                .tableName("ПРЯМОЕ КОМБАЙНИРОВАНИЕ ЗЕРНОВЫХ С ИЗМЕЛЬЧЕНИЕМ СОЛОМЫ")
                                .combine("CLAAS LEXION-760 - 461 л.с.")
                                .weightRatioGrainToStraw("1:2")
                                .yield("3.3...3.5")
                                .workingWidth("9")
                                .routingLength("601-1000")
                                .build())
                        .expected(new Fuel(89.5, 3.2))
                        .build(),
                FuelSearchingArguments.builder()
                        .specification(FuelSpecification.builder()
                                .tableName("ПРЯМОЕ КОМБАЙНИРОВАНИЕ ЗЕРНОВЫХ С ИЗМЕЛЬЧЕНИЕМ СОЛОМЫ")
                                .combine("КЗС-3219 КР \"ПАЛЕССЕ GS-3219 КР\" - 390 л.с.")
                                .weightRatioGrainToStraw("1:1")
                                .yield("До 1.4")
                                .workingWidth("7")
                                .routingLength("Менее 150")
                                .build())
                        .expected(new Fuel(18.7, 13))
                        .build(),
                FuelSearchingArguments.builder()
                        .specification(FuelSpecification.builder()
                                .tableName("ПРЯМОЕ КОМБАЙНИРОВАНИЕ ЗЕРНОВЫХ С ИЗМЕЛЬЧЕНИЕМ СОЛОМЫ")
                                .combine("КЗС-3219 КР \"ПАЛЕССЕ GS-3219 КР\" - 390 л.с.")
                                .weightRatioGrainToStraw("1:1")
                                .yield("4.1...4.5")
                                .workingWidth("7")
                                .routingLength("401-600")
                                .build())
                        .expected(new Fuel(65.3, 4.9))
                        .build(),
                FuelSearchingArguments.builder()
                        .specification(FuelSpecification.builder()
                                .tableName("ПРЯМОЕ КОМБАЙНИРОВАНИЕ ЗЕРНОВЫХ С ИЗМЕЛЬЧЕНИЕМ СОЛОМЫ")
                                .combine("КЗС-3219 КР \"ПАЛЕССЕ GS-3219 КР\" - 390 л.с.")
                                .weightRatioGrainToStraw("1:1.5")
                                .yield("4.8...5.1")
                                .workingWidth("7")
                                .routingLength("201-300")
                                .build())
                        .expected(new Fuel(60.8, 4.7))
                        .build(),
                FuelSearchingArguments.builder()
                        .specification(FuelSpecification.builder()
                                .tableName("ПРЯМОЕ КОМБАЙНИРОВАНИЕ ЗЕРНОВЫХ С ИЗМЕЛЬЧЕНИЕМ СОЛОМЫ")
                                .combine("КЗС-3219 КР \"ПАЛЕССЕ GS-3219 КР\" - 390 л.с.")
                                .weightRatioGrainToStraw("1:1.5")
                                .yield("1.8...2.1")
                                .workingWidth("7")
                                .routingLength("401-600")
                                .build())
                        .expected(new Fuel(46.7, 6.9))
                        .build(),
                FuelSearchingArguments.builder()
                        .specification(FuelSpecification.builder()
                                .tableName("ПРЯМОЕ КОМБАЙНИРОВАНИЕ ЗЕРНОВЫХ С ИЗМЕЛЬЧЕНИЕМ СОЛОМЫ")
                                .combine("КЗС-3219 КР \"ПАЛЕССЕ GS-3219 КР\" - 390 л.с.")
                                .weightRatioGrainToStraw("1:2")
                                .yield("1.8...2")
                                .workingWidth("7")
                                .routingLength("201-300")
                                .build())
                        .expected(new Fuel(41.2, 7))
                        .build(),
                FuelSearchingArguments.builder()
                        .specification(FuelSpecification.builder()
                                .tableName("ПРЯМОЕ КОМБАЙНИРОВАНИЕ ЗЕРНОВЫХ С ИЗМЕЛЬЧЕНИЕМ СОЛОМЫ")
                                .combine("КЗС-3219 КР \"ПАЛЕССЕ GS-3219 КР\" - 390 л.с.")
                                .weightRatioGrainToStraw("1:2")
                                .yield("3.5...3.7")
                                .workingWidth("7")
                                .routingLength("601-1000")
                                .build())
                        .expected(new Fuel(79.1, 4.2))
                        .build(),
                FuelSearchingArguments.builder()
                        .specification(FuelSpecification.builder()
                                .tableName("ПРЯМОЕ КОМБАЙНИРОВАНИЕ ЗЕРНОВЫХ С ИЗМЕЛЬЧЕНИЕМ СОЛОМЫ")
                                .combine("CLAAS LEXION-560 - 360 л.с.")
                                .weightRatioGrainToStraw("1:1")
                                .yield("До 1.4")
                                .workingWidth("6.6")
                                .routingLength("Менее 150")
                                .build())
                        .expected(new Fuel(16.8, 11.7))
                        .build(),
                FuelSearchingArguments.builder()
                        .specification(FuelSpecification.builder()
                                .tableName("ПРЯМОЕ КОМБАЙНИРОВАНИЕ ЗЕРНОВЫХ С ИЗМЕЛЬЧЕНИЕМ СОЛОМЫ")
                                .combine("CLAAS LEXION-560 - 360 л.с.")
                                .weightRatioGrainToStraw("1:1")
                                .yield("4.9...5.3")
                                .workingWidth("6.6")
                                .routingLength("301-400")
                                .build())
                        .expected(new Fuel(64, 3.9))
                        .build(),
                FuelSearchingArguments.builder()
                        .specification(FuelSpecification.builder()
                                .tableName("ПРЯМОЕ КОМБАЙНИРОВАНИЕ ЗЕРНОВЫХ С ИЗМЕЛЬЧЕНИЕМ СОЛОМЫ")
                                .combine("CLAAS LEXION-560 - 360 л.с.")
                                .weightRatioGrainToStraw("1:1.5")
                                .yield("3.6...3.9")
                                .workingWidth("6.6")
                                .routingLength("150-200")
                                .build())
                        .expected(new Fuel(42.8, 4.9))
                        .build(),
                FuelSearchingArguments.builder()
                        .specification(FuelSpecification.builder()
                                .tableName("ПРЯМОЕ КОМБАЙНИРОВАНИЕ ЗЕРНОВЫХ С ИЗМЕЛЬЧЕНИЕМ СОЛОМЫ")
                                .combine("CLAAS LEXION-560 - 360 л.с.")
                                .weightRatioGrainToStraw("1:1.5")
                                .yield("4.8...5.1")
                                .workingWidth("6.6")
                                .routingLength("Более 1000")
                                .build())
                        .expected(new Fuel(81.1, 3.3))
                        .build(),
                FuelSearchingArguments.builder()
                        .specification(FuelSpecification.builder()
                                .tableName("ПРЯМОЕ КОМБАЙНИРОВАНИЕ ЗЕРНОВЫХ С ИЗМЕЛЬЧЕНИЕМ СОЛОМЫ")
                                .combine("CLAAS LEXION-560 - 360 л.с.")
                                .weightRatioGrainToStraw("1:2")
                                .yield("4...4.2")
                                .workingWidth("6.6")
                                .routingLength("150-200")
                                .build())
                        .expected(new Fuel(50.1, 4.1))
                        .build(),
                FuelSearchingArguments.builder()
                        .specification(FuelSpecification.builder()
                                .tableName("ПРЯМОЕ КОМБАЙНИРОВАНИЕ ЗЕРНОВЫХ С ИЗМЕЛЬЧЕНИЕМ СОЛОМЫ")
                                .combine("CLAAS LEXION-560 - 360 л.с.")
                                .weightRatioGrainToStraw("1:2")
                                .yield("4.7...5")
                                .workingWidth("6.6")
                                .routingLength("301-400")
                                .build())
                        .expected(new Fuel(82.2, 3))
                        .build(),
                FuelSearchingArguments.builder()
                        .specification(FuelSpecification.builder()
                                .tableName("ПРЯМОЕ КОМБАЙНИРОВАНИЕ ЗЕРНОВЫХ С ИЗМЕЛЬЧЕНИЕМ СОЛОМЫ")
                                .combine("JOHN DEERE 9640WTS-770 - 524 л.с.")
                                .weightRatioGrainToStraw("1:1")
                                .yield("До 1.4")
                                .workingWidth("6")
                                .routingLength("Менее 150")
                                .build())
                        .expected(new Fuel(13.8, 12))
                        .build(),
                FuelSearchingArguments.builder()
                        .specification(FuelSpecification.builder()
                                .tableName("ПРЯМОЕ КОМБАЙНИРОВАНИЕ ЗЕРНОВЫХ С ИЗМЕЛЬЧЕНИЕМ СОЛОМЫ")
                                .combine("JOHN DEERE 9640WTS-770 - 524 л.с.")
                                .weightRatioGrainToStraw("1:1")
                                .yield("4.5...4.9")
                                .workingWidth("6")
                                .routingLength("601-1000")
                                .build())
                        .expected(new Fuel(48.6, 3.8))
                        .build(),
                FuelSearchingArguments.builder()
                        .specification(FuelSpecification.builder()
                                .tableName("ПРЯМОЕ КОМБАЙНИРОВАНИЕ ЗЕРНОВЫХ С ИЗМЕЛЬЧЕНИЕМ СОЛОМЫ")
                                .combine("JOHN DEERE 9640WTS-770 - 524 л.с.")
                                .weightRatioGrainToStraw("1:1.5")
                                .yield("1.8...2.1")
                                .workingWidth("6")
                                .routingLength("301-400")
                                .build())
                        .expected(new Fuel(29.2, 6.3))
                        .build(),
                FuelSearchingArguments.builder()
                        .specification(FuelSpecification.builder()
                                .tableName("ПРЯМОЕ КОМБАЙНИРОВАНИЕ ЗЕРНОВЫХ С ИЗМЕЛЬЧЕНИЕМ СОЛОМЫ")
                                .combine("JOHN DEERE 9640WTS-770 - 524 л.с.")
                                .weightRatioGrainToStraw("1:1.5")
                                .yield("5.7...6")
                                .workingWidth("6")
                                .routingLength("150-200")
                                .build())
                        .expected(new Fuel(45.6, 3.6))
                        .build(),
                FuelSearchingArguments.builder()
                        .specification(FuelSpecification.builder()
                                .tableName("ПРЯМОЕ КОМБАЙНИРОВАНИЕ ЗЕРНОВЫХ С ИЗМЕЛЬЧЕНИЕМ СОЛОМЫ")
                                .combine("JOHN DEERE 9640WTS-770 - 524 л.с.")
                                .weightRatioGrainToStraw("1:2")
                                .yield("0.9...1.2")
                                .workingWidth("6")
                                .routingLength("401-600")
                                .build())
                        .expected(new Fuel(23.9, 7.7))
                        .build(),
                FuelSearchingArguments.builder()
                        .specification(FuelSpecification.builder()
                                .tableName("ПРЯМОЕ КОМБАЙНИРОВАНИЕ ЗЕРНОВЫХ С ИЗМЕЛЬЧЕНИЕМ СОЛОМЫ")
                                .combine("JOHN DEERE 9640WTS-770 - 524 л.с.")
                                .weightRatioGrainToStraw("1:2")
                                .yield("4.5...4.7")
                                .workingWidth("6")
                                .routingLength("150-200")
                                .build())
                        .expected(new Fuel(43.8, 3.8))
                        .build(),
                //not existing combine
                FuelSearchingArguments.builder()
                        .specification(FuelSpecification.builder()
                                .tableName("ПРЯМОЕ КОМБАЙНИРОВАНИЕ ЗЕРНОВЫХ С ИЗМЕЛЬЧЕНИЕМ СОЛОМЫ")
                                .combine("not existing")
                                .weightRatioGrainToStraw("1:2")
                                .yield("4.5...4.7")
                                .workingWidth("6")
                                .routingLength("150-200")
                                .build())
                        .build(),
                //not existing weight ratio grain to straw
                FuelSearchingArguments.builder()
                        .specification(FuelSpecification.builder()
                                .tableName("ПРЯМОЕ КОМБАЙНИРОВАНИЕ ЗЕРНОВЫХ С ИЗМЕЛЬЧЕНИЕМ СОЛОМЫ")
                                .combine("JOHN DEERE 9640WTS-770 - 524 л.с.")
                                .weightRatioGrainToStraw("not existing")
                                .yield("4.5...4.7")
                                .workingWidth("6")
                                .routingLength("150-200")
                                .build())
                        .build(),
                //not existing yield
                FuelSearchingArguments.builder()
                        .specification(FuelSpecification.builder()
                                .tableName("ПРЯМОЕ КОМБАЙНИРОВАНИЕ ЗЕРНОВЫХ С ИЗМЕЛЬЧЕНИЕМ СОЛОМЫ")
                                .combine("JOHN DEERE 9640WTS-770 - 524 л.с.")
                                .weightRatioGrainToStraw("1:2")
                                .yield("not existing")
                                .workingWidth("6")
                                .routingLength("150-200")
                                .build())
                        .build(),
                //not existing working width
                FuelSearchingArguments.builder()
                        .specification(FuelSpecification.builder()
                                .tableName("ПРЯМОЕ КОМБАЙНИРОВАНИЕ ЗЕРНОВЫХ С ИЗМЕЛЬЧЕНИЕМ СОЛОМЫ")
                                .combine("JOHN DEERE 9640WTS-770 - 524 л.с.")
                                .weightRatioGrainToStraw("1:2")
                                .yield("4.5...4.7")
                                .workingWidth("not existing")
                                .routingLength("150-200")
                                .build())
                        .build(),
                //not existing routing length
                FuelSearchingArguments.builder()
                        .specification(FuelSpecification.builder()
                                .tableName("ПРЯМОЕ КОМБАЙНИРОВАНИЕ ЗЕРНОВЫХ С ИЗМЕЛЬЧЕНИЕМ СОЛОМЫ")
                                .combine("JOHN DEERE 9640WTS-770 - 524 л.с.")
                                .weightRatioGrainToStraw("1:2")
                                .yield("4.5...4.7")
                                .workingWidth("6")
                                .routingLength("not existing")
                                .build())
                        .build()
        );
    }

}
