fuel-document:
  path: ./src/main/resources/fuel-document.docx

fuel-searcher-config:
  path: ./src/main/resources/fuel-searchers.xml

metadata:
  refresh-on-start: true
  file-path: ./src/main/resources/tables-metadata.txt
