fuel-document:
  path: ./src/main/resources/fuel-document.docx

fuel-searcher-config:
  path: ./src/main/resources/searcher-config.xml

metadata:
  refresh-on-start: true
  file-path: ./src/main/resources/tables-metadata.txt

server:
  servlet:
    context-path: /fuel-searcher
