spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fuel_searcher
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        generate_statistics: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 20
    show-sql: true

fuel-document:
  path: ./src/main/resources/postanovlenie128.2022.docx

fuel-searcher-config:
  path : ./src/main/resources/fuel-searchers.xml

meta-data-refreshing:
  enable: true
