package com.aurorasoft.fuelsearcher.it.fuelsearching.argumentsprovider.success;

import com.aurorasoft.fuelsearcher.it.fuelsearching.argumentsprovider.model.SuccessFuelSearchingArguments;
import com.aurorasoft.fuelsearcher.model.Fuel;
import com.aurorasoft.fuelsearcher.model.specification.FuelSpecification.FuelSpecificationBuilder;

import java.util.function.Supplier;
import java.util.stream.Stream;

public final class ThirteenthSuccessTableFuelSearchingArgumentsProvider extends SuccessTableFuelSearchingArgumentsProvider {
    private static final String TABLE_NAME = "ВНЕСЕНИЕ ОРГАНИЧЕСКИХ УДОБРЕНИЙ";

    public ThirteenthSuccessTableFuelSearchingArgumentsProvider() {
        super(TABLE_NAME);
    }

    @Override
    protected Stream<SuccessFuelSearchingArguments> createArguments(final Supplier<FuelSpecificationBuilder> specificationBuilderSupplier) {
        return Stream.of(
                SuccessFuelSearchingArguments.builder()
                        .specification(specificationBuilderSupplier.get()
                                .tractor("БЕЛАРУС 3522")
                                .machinery("РОУМ-24")
                                .cargoClass("Грузы I класса")
                                .roadGroup("Первая группа дорог")
                                .transportDistance("0.25...0.75")
                                .spreadRate("Менее 30")
                                .build())
                        .expected(new Fuel(259.8, 0.4))
                        .build(),
                SuccessFuelSearchingArguments.builder()
                        .specification(specificationBuilderSupplier.get()
                                .tractor("БЕЛАРУС 3522")
                                .machinery("РОУМ-24")
                                .cargoClass("Грузы I класса")
                                .roadGroup("Вторая группа дорог")
                                .transportDistance("6.1...7")
                                .spreadRate("30-50")
                                .build())
                        .expected(new Fuel(143.5, 1.17))
                        .build(),
                SuccessFuelSearchingArguments.builder()
                        .specification(specificationBuilderSupplier.get()
                                .tractor("БЕЛАРУС 3522")
                                .machinery("РОУМ-24")
                                .cargoClass("Грузы I класса")
                                .roadGroup("Третья группа дорог")
                                .transportDistance("0.76...1.25")
                                .spreadRate("Более 50")
                                .build())
                        .expected(new Fuel(255.1, 0.4))
                        .build(),
                SuccessFuelSearchingArguments.builder()
                        .specification(specificationBuilderSupplier.get()
                                .tractor("БЕЛАРУС 3522")
                                .machinery("РОУМ-24")
                                .cargoClass("Грузы II класса")
                                .roadGroup("Первая группа дорог")
                                .transportDistance("18.1...21")
                                .spreadRate("30-50")
                                .build())
                        .expected(new Fuel(65.3, 2.83))
                        .build(),
                SuccessFuelSearchingArguments.builder()
                        .specification(specificationBuilderSupplier.get()
                                .tractor("БЕЛАРУС 3522")
                                .machinery("РОУМ-24")
                                .cargoClass("Грузы II класса")
                                .roadGroup("Вторая группа дорог")
                                .transportDistance("0.76...1.25")
                                .spreadRate("Более 50")
                                .build())
                        .expected(new Fuel(225.7, 0.39))
                        .build(),
                SuccessFuelSearchingArguments.builder()
                        .specification(specificationBuilderSupplier.get()
                                .tractor("БЕЛАРУС 3522")
                                .machinery("РОУМ-24")
                                .cargoClass("Грузы II класса")
                                .roadGroup("Третья группа дорог")
                                .transportDistance("18.1...21")
                                .spreadRate("Менее 30")
                                .build())
                        .expected(new Fuel(47.6, 4.6))
                        .build(),
                SuccessFuelSearchingArguments.builder()
                        .specification(specificationBuilderSupplier.get()
                                .tractor("JOHN DEERE 8430")
                                .machinery("МТУ-24")
                                .cargoClass("Грузы I класса")
                                .roadGroup("Первая группа дорог")
                                .transportDistance("0.25...0.75")
                                .spreadRate("Менее 30")
                                .build())
                        .expected(new Fuel(253.9, 0.39))
                        .build(),
                SuccessFuelSearchingArguments.builder()
                        .specification(specificationBuilderSupplier.get()
                                .tractor("JOHN DEERE 8430")
                                .machinery("МТУ-24")
                                .cargoClass("Грузы I класса")
                                .roadGroup("Вторая группа дорог")
                                .transportDistance("21.1...24")
                                .spreadRate("30-50")
                                .build())
                        .expected(new Fuel(56.7, 3.53))
                        .build(),
                SuccessFuelSearchingArguments.builder()
                        .specification(specificationBuilderSupplier.get()
                                .tractor("JOHN DEERE 8430")
                                .machinery("МТУ-24")
                                .cargoClass("Грузы I класса")
                                .roadGroup("Третья группа дорог")
                                .transportDistance("6.1...7")
                                .spreadRate("Более 50")
                                .build())
                        .expected(new Fuel(125.9, 1.36))
                        .build(),
                SuccessFuelSearchingArguments.builder()
                        .specification(specificationBuilderSupplier.get()
                                .tractor("JOHN DEERE 8430")
                                .machinery("МТУ-24")
                                .cargoClass("Грузы II класса")
                                .roadGroup("Первая группа дорог")
                                .transportDistance("5.1...6")
                                .spreadRate("Более 50")
                                .build())
                        .expected(new Fuel(139.3, 0.93))
                        .build(),
                SuccessFuelSearchingArguments.builder()
                        .specification(specificationBuilderSupplier.get()
                                .tractor("JOHN DEERE 8430")
                                .machinery("МТУ-24")
                                .cargoClass("Грузы II класса")
                                .roadGroup("Вторая группа дорог")
                                .transportDistance("14.1...16")
                                .spreadRate("30-50")
                                .build())
                        .expected(new Fuel(65.7, 2.76))
                        .build(),
                SuccessFuelSearchingArguments.builder()
                        .specification(specificationBuilderSupplier.get()
                                .tractor("JOHN DEERE 8430")
                                .machinery("МТУ-24")
                                .cargoClass("Грузы II класса")
                                .roadGroup("Третья группа дорог")
                                .transportDistance("28.1...32")
                                .spreadRate("Менее 30")
                                .build())
                        .expected(new Fuel(30.9, 6.94))
                        .build(),
                SuccessFuelSearchingArguments.builder()
                        .specification(specificationBuilderSupplier.get()
                                .tractor("БЕЛАРУС 3022")
                                .machinery("МТУ-20")
                                .cargoClass("Грузы I класса")
                                .roadGroup("Первая группа дорог")
                                .transportDistance("1.76...2.25")
                                .spreadRate("Менее 30")
                                .build())
                        .expected(new Fuel(198., 0.49))
                        .build(),
                SuccessFuelSearchingArguments.builder()
                        .specification(specificationBuilderSupplier.get()
                                .tractor("БЕЛАРУС 3022")
                                .machinery("МТУ-20")
                                .cargoClass("Грузы I класса")
                                .roadGroup("Вторая группа дорог")
                                .transportDistance("1.76...2.25")
                                .spreadRate("Менее 30")
                                .build())
                        .expected(new Fuel(188.6, 0.55))
                        .build(),
                SuccessFuelSearchingArguments.builder()
                        .specification(specificationBuilderSupplier.get()
                                .tractor("БЕЛАРУС 3022")
                                .machinery("МТУ-20")
                                .cargoClass("Грузы I класса")
                                .roadGroup("Третья группа дорог")
                                .transportDistance("16.1...18")
                                .spreadRate("Более 50")
                                .build())
                        .expected(new Fuel(50.5, 3.7))
                        .build(),
                SuccessFuelSearchingArguments.builder()
                        .specification(specificationBuilderSupplier.get()
                                .tractor("БЕЛАРУС 3022")
                                .machinery("МТУ-20")
                                .cargoClass("Грузы II класса")
                                .roadGroup("Первая группа дорог")
                                .transportDistance("3.26...4")
                                .spreadRate("Менее 30")
                                .build())
                        .expected(new Fuel(139.8, 0.76))
                        .build(),
                SuccessFuelSearchingArguments.builder()
                        .specification(specificationBuilderSupplier.get()
                                .tractor("БЕЛАРУС 3022")
                                .machinery("МТУ-20")
                                .cargoClass("Грузы II класса")
                                .roadGroup("Вторая группа дорог")
                                .transportDistance("8.1...9")
                                .spreadRate("30-50")
                                .build())
                        .expected(new Fuel(82.9, 1.72))
                        .build(),
                SuccessFuelSearchingArguments.builder()
                        .specification(specificationBuilderSupplier.get()
                                .tractor("БЕЛАРУС 3022")
                                .machinery("МТУ-20")
                                .cargoClass("Грузы II класса")
                                .roadGroup("Третья группа дорог")
                                .transportDistance("18.1...21")
                                .spreadRate("Более 50")
                                .build())
                        .expected(new Fuel(38.9, 4.58))
                        .build(),
                SuccessFuelSearchingArguments.builder()
                        .specification(specificationBuilderSupplier.get()
                                .tractor("JOHN DEERE 6930")
                                .machinery("РОУМ-14")
                                .cargoClass("Грузы I класса")
                                .roadGroup("Первая группа дорог")
                                .transportDistance("2.76...3.25")
                                .spreadRate("Менее 30")
                                .build())
                        .expected(new Fuel(139.1, 0.59))
                        .build(),
                SuccessFuelSearchingArguments.builder()
                        .specification(specificationBuilderSupplier.get()
                                .tractor("JOHN DEERE 6930")
                                .machinery("РОУМ-14")
                                .cargoClass("Грузы I класса")
                                .roadGroup("Вторая группа дорог")
                                .transportDistance("10.1...12")
                                .spreadRate("30-50")
                                .build())
                        .expected(new Fuel(57.7, 2.23))
                        .build(),
                SuccessFuelSearchingArguments.builder()
                        .specification(specificationBuilderSupplier.get()
                                .tractor("JOHN DEERE 6930")
                                .machinery("РОУМ-14")
                                .cargoClass("Грузы I класса")
                                .roadGroup("Третья группа дорог")
                                .transportDistance("21.1...24")
                                .spreadRate("Более 50")
                                .build())
                        .expected(new Fuel(26.5, 5.7))
                        .build(),
                SuccessFuelSearchingArguments.builder()
                        .specification(specificationBuilderSupplier.get()
                                .tractor("JOHN DEERE 6930")
                                .machinery("РОУМ-14")
                                .cargoClass("Грузы II класса")
                                .roadGroup("Первая группа дорог")
                                .transportDistance("8.1...9")
                                .spreadRate("Менее 30")
                                .build())
                        .expected(new Fuel(66.7, 1.62))
                        .build(),
                SuccessFuelSearchingArguments.builder()
                        .specification(specificationBuilderSupplier.get()
                                .tractor("JOHN DEERE 6930")
                                .machinery("РОУМ-14")
                                .cargoClass("Грузы II класса")
                                .roadGroup("Вторая группа дорог")
                                .transportDistance("8.1...9")
                                .spreadRate("30-50")
                                .build())
                        .expected(new Fuel(59, 1.95))
                        .build(),
                SuccessFuelSearchingArguments.builder()
                        .specification(specificationBuilderSupplier.get()
                                .tractor("JOHN DEERE 6930")
                                .machinery("РОУМ-14")
                                .cargoClass("Грузы II класса")
                                .roadGroup("Третья группа дорог")
                                .transportDistance("16.1...18")
                                .spreadRate("Более 50")
                                .build())
                        .expected(new Fuel(28.6, 4.97))
                        .build()
        );
    }
}
